// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DoorsColumns holds the columns for the "doors" table.
	DoorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "direction", Type: field.TypeEnum, Enums: []string{"north", "south", "east", "west", "up", "down"}},
		{Name: "door_from", Type: field.TypeString, Nullable: true},
		{Name: "door_to", Type: field.TypeString, Nullable: true},
	}
	// DoorsTable holds the schema information for the "doors" table.
	DoorsTable = &schema.Table{
		Name:       "doors",
		Columns:    DoorsColumns,
		PrimaryKey: []*schema.Column{DoorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doors_rooms_from",
				Columns:    []*schema.Column{DoorsColumns[4]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "doors_rooms_to",
				Columns:    []*schema.Column{DoorsColumns[5]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EntitiesColumns holds the columns for the "entities" table.
	EntitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// EntitiesTable holds the schema information for the "entities" table.
	EntitiesTable = &schema.Table{
		Name:       "entities",
		Columns:    EntitiesColumns,
		PrimaryKey: []*schema.Column{EntitiesColumns[0]},
	}
	// PlayersColumns holds the columns for the "players" table.
	PlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "room_players", Type: field.TypeString, Nullable: true},
	}
	// PlayersTable holds the schema information for the "players" table.
	PlayersTable = &schema.Table{
		Name:       "players",
		Columns:    PlayersColumns,
		PrimaryKey: []*schema.Column{PlayersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "players_rooms_players",
				Columns:    []*schema.Column{PlayersColumns[5]},
				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PlayerRolesColumns holds the columns for the "player_roles" table.
	PlayerRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PlayerRolesTable holds the schema information for the "player_roles" table.
	PlayerRolesTable = &schema.Table{
		Name:       "player_roles",
		Columns:    PlayerRolesColumns,
		PrimaryKey: []*schema.Column{PlayerRolesColumns[0]},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
	}
	// PlayerPlayerRolesColumns holds the columns for the "player_player_roles" table.
	PlayerPlayerRolesColumns = []*schema.Column{
		{Name: "player_id", Type: field.TypeString},
		{Name: "player_role_id", Type: field.TypeInt},
	}
	// PlayerPlayerRolesTable holds the schema information for the "player_player_roles" table.
	PlayerPlayerRolesTable = &schema.Table{
		Name:       "player_player_roles",
		Columns:    PlayerPlayerRolesColumns,
		PrimaryKey: []*schema.Column{PlayerPlayerRolesColumns[0], PlayerPlayerRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "player_player_roles_player_id",
				Columns:    []*schema.Column{PlayerPlayerRolesColumns[0]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "player_player_roles_player_role_id",
				Columns:    []*schema.Column{PlayerPlayerRolesColumns[1]},
				RefColumns: []*schema.Column{PlayerRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DoorsTable,
		EntitiesTable,
		PlayersTable,
		PlayerRolesTable,
		RoomsTable,
		PlayerPlayerRolesTable,
	}
)

func init() {
	DoorsTable.ForeignKeys[0].RefTable = RoomsTable
	DoorsTable.ForeignKeys[1].RefTable = RoomsTable
	PlayersTable.ForeignKeys[0].RefTable = RoomsTable
	PlayerPlayerRolesTable.ForeignKeys[0].RefTable = PlayersTable
	PlayerPlayerRolesTable.ForeignKeys[1].RefTable = PlayerRolesTable
}
