// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/smxlong/mud/ent/player"
	"github.com/smxlong/mud/ent/playerrole"
	"github.com/smxlong/mud/ent/predicate"
)

// PlayerRoleUpdate is the builder for updating PlayerRole entities.
type PlayerRoleUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerRoleMutation
}

// Where appends a list predicates to the PlayerRoleUpdate builder.
func (pru *PlayerRoleUpdate) Where(ps ...predicate.PlayerRole) *PlayerRoleUpdate {
	pru.mutation.Where(ps...)
	return pru
}

// SetName sets the "name" field.
func (pru *PlayerRoleUpdate) SetName(s string) *PlayerRoleUpdate {
	pru.mutation.SetName(s)
	return pru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pru *PlayerRoleUpdate) SetNillableName(s *string) *PlayerRoleUpdate {
	if s != nil {
		pru.SetName(*s)
	}
	return pru
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (pru *PlayerRoleUpdate) AddPlayerIDs(ids ...string) *PlayerRoleUpdate {
	pru.mutation.AddPlayerIDs(ids...)
	return pru
}

// AddPlayers adds the "players" edges to the Player entity.
func (pru *PlayerRoleUpdate) AddPlayers(p ...*Player) *PlayerRoleUpdate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pru.AddPlayerIDs(ids...)
}

// Mutation returns the PlayerRoleMutation object of the builder.
func (pru *PlayerRoleUpdate) Mutation() *PlayerRoleMutation {
	return pru.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (pru *PlayerRoleUpdate) ClearPlayers() *PlayerRoleUpdate {
	pru.mutation.ClearPlayers()
	return pru
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (pru *PlayerRoleUpdate) RemovePlayerIDs(ids ...string) *PlayerRoleUpdate {
	pru.mutation.RemovePlayerIDs(ids...)
	return pru
}

// RemovePlayers removes "players" edges to Player entities.
func (pru *PlayerRoleUpdate) RemovePlayers(p ...*Player) *PlayerRoleUpdate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pru.RemovePlayerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pru *PlayerRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pru.sqlSave, pru.mutation, pru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pru *PlayerRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := pru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pru *PlayerRoleUpdate) Exec(ctx context.Context) error {
	_, err := pru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pru *PlayerRoleUpdate) ExecX(ctx context.Context) {
	if err := pru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pru *PlayerRoleUpdate) check() error {
	if v, ok := pru.mutation.Name(); ok {
		if err := playerrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlayerRole.name": %w`, err)}
		}
	}
	return nil
}

func (pru *PlayerRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerrole.Table, playerrole.Columns, sqlgraph.NewFieldSpec(playerrole.FieldID, field.TypeInt))
	if ps := pru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pru.mutation.Name(); ok {
		_spec.SetField(playerrole.FieldName, field.TypeString, value)
	}
	if pru.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pru.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !pru.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pru.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pru.mutation.done = true
	return n, nil
}

// PlayerRoleUpdateOne is the builder for updating a single PlayerRole entity.
type PlayerRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerRoleMutation
}

// SetName sets the "name" field.
func (pruo *PlayerRoleUpdateOne) SetName(s string) *PlayerRoleUpdateOne {
	pruo.mutation.SetName(s)
	return pruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pruo *PlayerRoleUpdateOne) SetNillableName(s *string) *PlayerRoleUpdateOne {
	if s != nil {
		pruo.SetName(*s)
	}
	return pruo
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (pruo *PlayerRoleUpdateOne) AddPlayerIDs(ids ...string) *PlayerRoleUpdateOne {
	pruo.mutation.AddPlayerIDs(ids...)
	return pruo
}

// AddPlayers adds the "players" edges to the Player entity.
func (pruo *PlayerRoleUpdateOne) AddPlayers(p ...*Player) *PlayerRoleUpdateOne {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pruo.AddPlayerIDs(ids...)
}

// Mutation returns the PlayerRoleMutation object of the builder.
func (pruo *PlayerRoleUpdateOne) Mutation() *PlayerRoleMutation {
	return pruo.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (pruo *PlayerRoleUpdateOne) ClearPlayers() *PlayerRoleUpdateOne {
	pruo.mutation.ClearPlayers()
	return pruo
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (pruo *PlayerRoleUpdateOne) RemovePlayerIDs(ids ...string) *PlayerRoleUpdateOne {
	pruo.mutation.RemovePlayerIDs(ids...)
	return pruo
}

// RemovePlayers removes "players" edges to Player entities.
func (pruo *PlayerRoleUpdateOne) RemovePlayers(p ...*Player) *PlayerRoleUpdateOne {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pruo.RemovePlayerIDs(ids...)
}

// Where appends a list predicates to the PlayerRoleUpdate builder.
func (pruo *PlayerRoleUpdateOne) Where(ps ...predicate.PlayerRole) *PlayerRoleUpdateOne {
	pruo.mutation.Where(ps...)
	return pruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pruo *PlayerRoleUpdateOne) Select(field string, fields ...string) *PlayerRoleUpdateOne {
	pruo.fields = append([]string{field}, fields...)
	return pruo
}

// Save executes the query and returns the updated PlayerRole entity.
func (pruo *PlayerRoleUpdateOne) Save(ctx context.Context) (*PlayerRole, error) {
	return withHooks(ctx, pruo.sqlSave, pruo.mutation, pruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pruo *PlayerRoleUpdateOne) SaveX(ctx context.Context) *PlayerRole {
	node, err := pruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pruo *PlayerRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := pruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pruo *PlayerRoleUpdateOne) ExecX(ctx context.Context) {
	if err := pruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pruo *PlayerRoleUpdateOne) check() error {
	if v, ok := pruo.mutation.Name(); ok {
		if err := playerrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlayerRole.name": %w`, err)}
		}
	}
	return nil
}

func (pruo *PlayerRoleUpdateOne) sqlSave(ctx context.Context) (_node *PlayerRole, err error) {
	if err := pruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerrole.Table, playerrole.Columns, sqlgraph.NewFieldSpec(playerrole.FieldID, field.TypeInt))
	id, ok := pruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayerRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playerrole.FieldID)
		for _, f := range fields {
			if !playerrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playerrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pruo.mutation.Name(); ok {
		_spec.SetField(playerrole.FieldName, field.TypeString, value)
	}
	if pruo.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pruo.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !pruo.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pruo.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   playerrole.PlayersTable,
			Columns: playerrole.PlayersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlayerRole{config: pruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pruo.mutation.done = true
	return _node, nil
}
