// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
